apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: kubeappdrupal
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
